### ISSUE TITLE
Validator why using the code

### ISSUE THREAD

**Issue by tinkerbaj** [wpcodevo/golang-fiber-jwt#1]
When you doing validation You are using this code
```
func ValidateStruct[T any](payload T) []*ErrorResponse {
	var errors []*ErrorResponse
	err := validate.Struct(payload)
	if err != nil {
		for _, err := range err.(validator.ValidationErrors) {
			var element ErrorResponse
			element.Field = err.StructNamespace()
			element.Tag = err.Tag()
			element.Value = err.Param()
			errors = append(errors, &element)
		}
	}
	return errors
}
```
Can you tell me what is benefit over using tags in struct?
And quick question are you plan to use go sveltekit auth tutorial with refresh token etc?

I love your tutorials so much

**Comment by wpcodevo** [comment]
> When you doing validation You are using this code
> 
> ```
> func ValidateStruct[T any](payload T) []*ErrorResponse {
> 	var errors []*ErrorResponse
> 	err := validate.Struct(payload)
> 	if err != nil {
> 		for _, err := range err.(validator.ValidationErrors) {
> 			var element ErrorResponse
> 			element.Field = err.StructNamespace()
> 			element.Tag = err.Tag()
> 			element.Value = err.Param()
> 			errors = append(errors, &element)
> 		}
> 	}
> 	return errors
> }
> ```
> 
> Can you tell me what is benefit over using tags in struct? And quick question are you plan to use go sveltekit auth tutorial with refresh token etc?
> 
> I love your tutorials so much

The Struct includes `validate` tags that specify the necessary validation rules for each field. However, the tags alone are not sufficient to validate the fields. Instead, we must create a function that utilizes the `validator` package to validate the Struct based on these rules and return any resulting validation errors. 

This is why we implemented the `ValidateStruct` function, which accepts a Struct as input, performs validation, and returns any resulting validation errors.

If you are familiar with Gin Gonic, you may notice that it provides built-in support for validating Structs, eliminating the need for a separate validation function. However, this functionality is not available in Fiber, which is why we implemented our own validation function.

In response to your second question, I appreciate your interest in a tutorial on implementing refresh tokens with SvelteKit. I will certainly consider adding it to my list of planned topics.

**Comment by wpcodevo** [comment]
I am now closing this issue. If you have any further questions or concerns, feel free to open a new issue.
